* Advanced Vue Component Design

** Building Controlled Component
   Learn the fundamentals of component communication best practices, and how you can use that knowledge to create you own components that work with Vue's v-model dricetive.
  [[/Users/yjh/Documents/tutorials/advanced-vue/1. Building Controlled Components.mp4][File]], [[https://codesandbox.io/s/oxxlx055xy?from-embed][Code]]

** Customizing Controlled Component Bindings
   Learn how to customize v-model so you can use more expressive names in your controlled components.
   [[~/Documents/tutorials/advanced-vue/2. Customizing Controlled Component Bindings.mp4][File]], [[https://codesandbox.io/s/mqnzm84plx?from-embed][Code]]

** Wrapping External Libraries as Vue Components
   There's a lot of high quality libraries out there designed to be used as just vanilla JS or as jQuery plugins. In this lesson your'll learn how to turn those libraries into Vue components so you can maintain a single JS paradigm within your own applications
   [[~/Documents/tutorials/advanced-vue/3. Wrapping External Libraries as Vue Components.mp4][File]], [[https://codesandbox.io/s/n4qolyr42m?from-embed][Code]]

** Encapsulating External Behavior: Closing on Escape
   In this lesson you'll learn and how it can sometimes be useful to break outside of Vue's built-in event handling system to write more portable components.
   [[~/Documents/tutorials/advanced-vue/4. Encapsulating External Behavior: Closing on Escape.mp4][File]], [[https://codesandbox.io/s/1v1o4lvp9j?from-embed][Code]]

** Encapsulating External Behavior: Background Scrolling
   Like event handling, sometimes you need to bypass Vue's activity system and do old-scholl DOM manipulation to keep a component's logic encapsulated. This lesson will teach you how and when to do it.
   [[~/Documents/tutorials/advanced-vue/5. Encapsulating External Behavior: Background Scrolling.mp4][File]], [[https://codesandbox.io/s/z0mx3w9km?from-embed][Code]]

** Encapsulating External Behavior: Portals
   When a single interaction involves multiple disconnected parts of the DOM(think a button that opens a modal that lives at the end of the body), a component's implementation details can quickly leak to other parts of your application and cause unnecessary coupling. Learn how you can use the portal pattern to avoid this.
   [[~/Documents/tutorials/advanced-vue/6. Encapsulating External Behavior: Portals.mp4][File]], [[https://codesandbox.io/s/vy0k8283o5?from-embed][Code]]

** Encapsulating External Behavior: Reusing Portals
   Learn how to reuse generic portal targets to avoid leaking knowledge to the root component about what's actually being rendered.
   [[~/Documents/tutorials/advanced-vue/7. Encapsulating External Behavior: Reusing Portals.mp4][File]], [[https://codesandbox.io/s/xv1ooy9v1p?from-embed][Code]]

** Injecting Content Using Slots
   Learn the fundamentals of using slots to customize a component's content.
   [[~/Documents/tutorials/advanced-vue/8. Injecting Content Using Slots.mp4][File]], [[https://codesandbox.io/s/8x54ow4vl9?from-embed][Code]]

** Native-Style Buttons Using Slots and Class Merging
   In this lesson, you'll learn how to apply our knowledge of slots to build a custom button component that behaves just like a native HTML element.
   [[~/Documents/tutorials/advanced-vue/9. Native-Style Buttons Using Slots and Class Merging.mp4][File]], [[https://codesandbox.io/s/j4m180n11v?from-embed][Code]]
