* Advanced Eloquent
  Sure, you've learned the essientials of using Eloquent in your applications, but do you really understand what's going on under the hood? Well, that's specifically what we're interested in for this series. How do all the bits and pieces fit together?

** DONE Building the World
   CLOSED: [2018-07-24 Tue 20:25]
   - State "DONE"       from "STARTED"    [2018-07-24 Tue 20:25]
   Before we dive into Eloquent, let's build the world so that we may toy around. As part of the process, we'll create some migrations, models, and seed classes.
   - =composer self-update=
   - =sqlite3 storage/database.sqlite=

** DONE Use the Source, Luke
   CLOSED: [2018-07-24 Tue 20:38]
   - State "DONE"       from "STARTED"    [2018-07-24 Tue 20:38]
   Our starting point is a laughable one: =Post::find(1)=. It's literally the first thing you learn how to do with Eloquent. But, think about it, do you fully understand what happens behind the scenes, when you make this call?
   - =newQuery= is =Eloquent Builder=

** DONE Where the Hack is Where?
   CLOSED: [2018-07-24 Tue 21:02]
   - State "DONE"       from "STARTED"    [2018-07-24 Tue 21:02]
   Okay, so we can do things like =Post::where($args)=, but there's just one problem: where exactly is that =where= method stored? It's defintely not on our =Model= class!
   =__callStatic()=
   =__call()=

** DONE The Query Builder
   CLOSED: [2018-07-24 Tue 21:13]
   - State "DONE"       from "STARTED"    [2018-07-24 Tue 21:13]
   Okay, let's move to a lower level, and figure out how the query builder actually construct these SQL quires and passes them to PDO.
