* STARTED How to Manage an Open Source Project
  Managing a popular open source project can be daunting at first. How do we maintain all these issues, or automatically trigger our test suit for incoming PRs? And what's a useful workflow for brainstorming and adding new features?
  In this series, together, we'll manage and maintain an open source forum, called *Council*, that we originally built from scratch here at Laracasts.
  
** DONE The GitHub Repository
   CLOSED: [2018-08-08 Wed 12:31]
   - State "DONE"       from "STARTED"    [2018-08-08 Wed 12:31]
   To begin this series, let's push our project to GitHub, so that anyone can install it - and even contribute to make it better.

** DONE Installation Instructions
   CLOSED: [2018-08-08 Wed 12:48]
   - State "DONE"       from "STARTED"    [2018-08-08 Wed 12:48]
   Our project will be of little use, if the general public doesn't know how to install it. Let's work through that entire process, while making installation notes for the project's readme file.

** DONE Resolving Our First Issue
   CLOSED: [2018-08-09 Thu 05:07]
   - State "DONE"       from "STARTED"    [2018-08-09 Thu 05:07]
   In the previous issue, we created our first GitHub issue: "Unconfirmed users should not be given the oppertunity to prepare create forum threads." Let's resolve that very issue in this episode.

** DONE The Issue and PR Grind
   CLOSED: [2018-08-09 Thu 05:28]
   - State "DONE"       from "STARTED"    [2018-08-09 Thu 05:28]
   We already have a number of issues and pull requests up on GitHub. Let's get to work on these, as we learn the basic day-to-day workflow for maintaining any open source project.
   - Resolve relating issuses using the =relosves #<issue-number>=  or =Fix #<issue-number>= syntax in commit message.

** DONE Feature: Forum Reputation
   CLOSED: [2018-08-09 Thu 05:53]
   - State "DONE"       from "STARTED"    [2018-08-09 Thu 05:53]
   Natuarlly, a core component to managing any open source project is intergrating new features and functionality. With that in mind, let's extend our forum with "user reputation". This way, for each participant in the forum, a number that indicates their participation and experience level may be assigned to them.
   - Tests
     - =a_user_earns_points_when_they_create_a_thread= in =ReputationTest=
     - =a_user_earns_points_when_they_reply_to_a_thread= in =ReputationTest=
     - =a_user_earns_points_when_they_reply_is_marked_as_best= in =ReputationTest=
