* Learn Vue2: Step by Step
  Vue is easily one of the most exciting additions to the front-end world in many years. With its intuitive API, and the fact that it can be applied to any type of application, it's no wonder why folks have gravitated to it as much as they have.
  If you'd like to jump on board, let me shou you, step by step, exactly you what you need to konw. It's the best way to learn Vue.

** 01 - Basic Data Binding
   Let's begin with a review of basic data binding in Vue. You'll get you first glimpse into the framework's wonderful, and automatic, reactivity.


   - Create a Vue instance
   - Bind dom root the Vue instance
   - Bind the dom element to instance data

** DONE 02 - Setup Vue Devtools
   CLOSED: [2018-07-04 Wed 22:38]
   - State "DONE"       from "STARTED"    [2018-07-04 Wed 22:38]
   Let's install =Vue Devtools= sooner, rather than later. As you'll see, this gives us a portal into any Vue instance on the page. Especially in these early stages, you'll get a lot of use out of this Chrome extension.
   - =$vm0.data-properties=
