* Learn Flexbox Through Examples
  Flexbox is easily one of the important additions to CSS in the last decade. The only problem is that there's a bit of a learning curve. Trust me, though: you want to learn this. And once you have, you'll be singing its praises to anyone who will listen. I guarantee it.

** A Perfectly Centered Logo
   Front-end designers have been joking about this for years. How again are you supposed to horizontally and vertically center a bit of content on the page? Before flexbox, it was kind of tough! No joke. Luckily, this is no longer the case. It's the easiest things the world now.
   - =display:flex=
   - =align-items:center=
   - =justify-content:center=

** A Navigation Menu
   For step two of your flexbox crash-course,we'll create a typically navigation menu, and then use flexbox to evenly distrubte each item with perfect precision.
   - =space-around=
   - =space-between=

** The Bread and Butter Layout
   Consider the most typical of website layouts: a head at the top, a main section - possible consists of a sidebar and primary content - in the middle, and then a footer stuck to the bottom. Traditionally, we've used the float to accomplished this layout. But the truth is that floats were never truly meant for this sort of thing. Luckily, again, there's a better way. In this episode, we'll discuss the =justify-content= property more, while reviewing the =margining-top:auto= trick.
   - =flex-drection: column=
   - =space-between= in =flex-drection: column= to define a layout.
