* Unlocking Badges Workshop

** Episode 1: Begin With an Example
   Like so mang things is life, starting a new feature is the hardest part. We're creating something out of nothing. It's not an easy task to define how that "something" should appear. But we'll try. Let's begin with one example of how the system should behave, using TDD.
** Episode 2: Event Fakery
   Let's drop down a level and write a test to ensure that, when experience is awarded to a user, an announcement (or event) is made to the rest of our application. Later, we'll listen for this announcement and grant any necessary achievement badges to the user.

** DONE Episode 3: Use TDD to Construct Migrations and Attributes
   CLOSED: [2018-07-07 Sat 05:56]
   - State "DONE"       from "STARTED"    [2018-07-07 Sat 05:56]
   It sounds like we'll need an =Achievement= Eloquent model, as well as its associated database table. Let's use TDD to construct both.
   - Create database attributes with TDD tests one by one.

** DONE Episode 4: A User Can Be Awarded Achievements
   CLOSED: [2018-07-07 Sat 06:11]
   - State "DONE"       from "STARTED"    [2018-07-07 Sat 06:11]
   In this episode, we'll construct the relationship between a user and their respective achievements. As you'll see, this is a prime use-case for a generic pivot table.
   - Use =$ahievement->awardedTo($user)=  mehtod but also =$user->awarded($achievement)= because it can make the =User.php= not more bigger.
