* STARTED What's New in Laravel 5.6
  Laravel 5.6 is upon us! While it's true that this release isn't quite as flashy, there are still an number of incredibly useful new additions and updates. Let's review them together.

** DONE Upgrading the Laracasts Codebase to Laravel 5.6
   CLOSED: [2018-07-20 Fri 16:41]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 16:41]
   Before we review the new additions to Laravel 5.6, let's begin by upgrading a real codebase from version 5.5 to 5.6. =As you'll find= with your own projects, some of the release notes will be relevant to your codebase, while others will not.

** DONE Broadcasts Channel Classes
   CLOSED: [2018-07-20 Fri 16:57]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 16:57]
   Laravel, for a while now, has included functionality for broadcasting server-side events over a WebSocket connection to the client-side. Often, as part of this process, it will prove necessary to authorize the current user. "Do they have permission to access this private channel or not?" Authorizations such as these are registered within your =routes/channels.php= file.
   If this file eventually becomes unwieldy, due to the number of authorizations, you may optionally extract the relevant logic to dedicated channel classes, using =php artisan make:channel=.

** DONE Collision Reporting
   CLOSED: [2018-07-20 Fri 17:02]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 17:02]
   Laravel 5.6 ships with drastically improved error reporting, when interacting with the framework through the console. In this lesson, we'll compare and contrast the exception output you'll see for an Artisan command in versions 5.5 and 5.6.
