* STARTED What's New in Laravel 5.6
  Laravel 5.6 is upon us! While it's true that this release isn't quite as flashy, there are still an number of incredibly useful new additions and updates. Let's review them together.

** DONE Upgrading the Laracasts Codebase to Laravel 5.6
   CLOSED: [2018-07-20 Fri 16:41]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 16:41]
   Before we review the new additions to Laravel 5.6, let's begin by upgrading a real codebase from version 5.5 to 5.6. =As you'll find= with your own projects, some of the release notes will be relevant to your codebase, while others will not.

** DONE Broadcasts Channel Classes
   CLOSED: [2018-07-20 Fri 16:57]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 16:57]
   Laravel, for a while now, has included functionality for broadcasting server-side events over a WebSocket connection to the client-side. Often, as part of this process, it will prove necessary to authorize the current user. "Do they have permission to access this private channel or not?" Authorizations such as these are registered within your =routes/channels.php= file.
   If this file eventually becomes unwieldy, due to the number of authorizations, you may optionally extract the relevant logic to dedicated channel classes, using =php artisan make:channel=.

** DONE Collision Reporting
   CLOSED: [2018-07-20 Fri 17:02]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 17:02]
   Laravel 5.6 ships with drastically improved error reporting, when interacting with the framework through the console. In this lesson, we'll compare and contrast the exception output you'll see for an Artisan command in versions 5.5 and 5.6.

** DONE Eloquent Date Casting
   CLOSED: [2018-07-20 Fri 17:09]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 17:09]
   When casting Eloquent attributes, you can now easily declare the format for your date columns. Maybe a particular date field, when converted to JSON, should be renderd as "January 1st" or "1/1/18". No problem.
   - =today()=
   - date cast
     #+BEGIN_SRC php
       protected $casts = [
           'expires_at' => 'date:Y-m-d'
       ];
     #+END_SRC

** DONE Improved Logging... Even to Slack
   CLOSED: [2018-07-20 Fri 17:25]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 17:25]
   Logging has been vastly improved in Laravel 5.6. You'll find a new =config/logging.php= file in a fresh install of laravel. Here, you may configure your desired default logging channel, or even specify a stack of channels. Maybe informational logs should be sent to the standard =laravel.log= file, while mission critical logs should be sent to Slack. Easy!
   - =Log::info('Hello World!')=

** DONE Dynamic Rate Limiting
   CLOSED: [2018-07-20 Fri 17:49]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 17:49]
   For a while now, Laravel has offered the ability to throttle the incoming requests. However, as part of Laravel 5.6, you can now dynamically configure the number of allowed attempts.
   =$rate_limit= in =User.php= model

** DONE Logout Other Devices
   CLOSED: [2018-07-20 Fri 18:01]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 18:01]
   Laravel now includes the useful =logoutOtherDevices= method on the =SessionGuard= class (=auth()->logoutOtherDevices()=). This means, with ease, you can invalidate all other sessions for a user's account. One use-case for this is ensuring that multiple people cannot log in and access the same account simultaneously. For a second example, but forgot to logout. No problem; you can offer the functionality to click a button invalidate that libary session.
   - =Illuminate\Session\Middleware\AuthenticateSession::class=
   - =auth()->logoutOtherDevices()=
