* STARTED What is New in Laravel 5.4
 It's that time of year again! Laravel in on the cusp of graduating to version 5.4. Along with it comes a variety of excellent optimizations and features. Markdown mail, higher order collection messages, Dusk, real-time facades... yes, please! In this series, I'll get you up to speed on what's new in laravel 5.4 as quickly as possible.

** DONE Sanitizing Middleware
   CLOSED: [2018-07-20 Fri 09:18]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 09:18]
   First up for this series is a review of two new middleware that are included with Laravel out of the box: =TrimStrings= and =ConvertEmptyStringToNull=. In effect, for every form request, Laravel will automatically trim any white space, while also converting all empty request fields to =null=.

** DONE Higher Order Collection Messages
   CLOSED: [2018-07-20 Fri 09:25]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 09:25]
   Laravel 5.4 includes support for higher order messaging, which is a fancy term that essientially breaks down to "collection shutcuts". What if, rather than filtering a collection, passing a clouser, and returning some data, you could simply type: =$collection->filter->isArchieved()= ? How cool is that? I'll show you how it all workes in this episode.

** DONE Laravel Mix in a Nutshell
   CLOSED: [2018-07-20 Fri 09:34]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 09:34]
   As part of Laravel 5.4, Laravel Elixir has been upgraded and renamed to Laravel Mix. While both versions will continue to exist, Mix should be your build tool wrapper of choice. It's build on Webpack, and provides nearly exact same friendly API that you're already used to.

** DONE Fluent Routing
   CLOSED: [2018-07-20 Fri 09:39]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 09:39]
   Laravel 5.4's routing component has been upgraded to support a more fluent routing syntax. No longer are you required to reference an array of awkward options, should you require a route group, prefix or name.

** DONE Resourceful Controllers With Model Boilerplate.
   CLOSED: [2018-07-20 Fri 09:49]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 09:49]
   When generating a controller from the command line (=php artisan make:controller=), you'll now find a new =--model= flag. When called with the name of a model, Laravel will automatically generate a resourceful controller that includes the necessary boilterplate to inject this model in all relevant controller actions.

** DONE Blade Components and Slots
   CLOSED: [2018-07-20 Fri 10:00]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 10:00]
   In Laravel 5.4, Blade offers a new =@component= directive. With this new addition, you may now, where relevant, think in terms of components and slots (much like Vue's implementation). Define a view partial, reference any necessary variables, and then call this component from any other view. It's probably best best if I simply show you!
