* STARTED What's New in Laravel 5.3
  It's about that time again! The release of Laravel 5.3 is imminent. That means, it's finally time to dig in and see what's new. And, well, there's a lot! From directory changes, to notifications, to passports, to everything in between!

** DONE Important Directory Changes
   CLOSED: [2018-07-19 Thu 10:50]
   - State "DONE"       from "STARTED"    [2018-07-19 Thu 10:50]
   Let's start off with some of the smaller changes, and then work our way up to the big additions! To begin you'll notice that your main directory structure is slightly different! A new routes folder at the top level? And what happened to the events, listeners, jobs, and policies folders? What's going on?

** DONE The Query Builder Now Returns Collections
   CLOSED: [2018-07-19 Thu 10:57]
   - State "DONE"       from "STARTED"    [2018-07-19 Thu 10:57]
   We're still taking it slow. What kind of series would it be if we discussed the coolest additions first? Anyways...next up, we have a small, but important change to be aware of. As of 5.3, all query builder calls will return Collection objects, rather than arrays. If you think about it, this make the general Laravel API more consistent, as relevant Eloquent calls already return Collection objects.

** DONE The Global Cache Helper
   CLOSED: [2018-07-19 Thu 11:05]
   - State "DONE"       from "STARTED"    [2018-07-19 Thu 11:05]
   In this episode, I'll introduce you to a funky little new =cache= global function! In 5.3, written by yours truly.
   - =cache=
     - =cache()=
     - =cache('foo', 'default')=
     - =cache(['foo' => 'bar'], 60)=
     - =cache(['user.1.vote' => [1, 2, 3]], 60)=
     - =cache()->put()=
     - =cache()->get()=
   - =session=
     - =session()=
     - =session(['foo' => 'bar'])=
     - =session('foo')=
     - =session('foox', 'default')=

** DONE The JavaScript Suggestion
   CLOSED: [2018-07-19 Thu 11:21]
   - State "DONE"       from "STARTED"    [2018-07-19 Thu 11:21]
   In Laravel 5.3, the framework makes a little suggestion on a practical JavaScript setup, using =Vue=. Have a look at your =resources/assets/js/= folder to check it out. It's important to note, however, that this is all entirely optional. If you prefer Ember or Backbone, delete the contents of you main =app.js= entry point, and you're good to go! It's only a suggestion.

** DONE Simpler Pagination
   CLOSED: [2018-07-19 Thu 11:34]
   - State "DONE"       from "STARTED"    [2018-07-19 Thu 11:34]
   Out of the box in Laravel 5.3, pagination will still feel very similar to you. However, should you need to modify the underlying HTML, the process is now significantly easier. In fact, you'll find that the process is very similar to how it was is Laravel 3!
   - =$user->links()=
