* STARTED What's New in Laravel 5.5
  Here we go again! Currently scheduled for an Augest release date, we're on the verge of Laravel 5.5. With that in mind, let's get a head start on the new features and additions to the framework. As always, there's quite a few!

** DONE Laravel 5.5 Installation and Whoops!
   CLOSED: [2018-07-20 Fri 10:53]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 10:53]
   Let's get started by *installing*, at the time of this recording, the development version of Laravel. That way, we can pull in the 5.5 version of the framework. Once setup, we'll also take a quick look at the new =Whoops= intergration.

** DONE Streamlined Request Validation
   CLOSED: [2018-07-20 Fri 11:05]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 11:05]
   A small, but long-requested addition, you may now send a =validate= message directly on your =Request= instance. Event better, this method call will return the validated data, which means you can pass the request directly to your model's =create= or =update= methods. Simpler code for the win!
   - CSRF exception: the page durning the inactive state.
   - Old validation workflow
     #+BEGIN_SRC php
       public function store()
       {
           $this->validate(request(), [
               'title' => 'required',
               'body' => 'required'
           ]);

           Post::create([request('title', 'body')]);

           return 'Done';
       }
     #+END_SRC
   - Now validation workflow
     #+BEGIN_SRC php
       public function store()
       {
           $validateData = request()->validate([
               'title' => 'required',
               'body' => 'required'
           ]);

           Post::create($validateData);

       }
     #+END_SRC

** DONE Fresh Migrations
   CLOSED: [2018-07-20 Fri 11:16]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 11:16]
   A new =migrate:fresh= Artisan command is being introduced as part of Laravel 5.5. This is similar to the existing =refresh= option, however, rather than rolling back all of your migrations (and triggering the respective =down= method for each), this new command will simply drow all tables and run your migrations fron scratch.

** DONE Frontend Presets
   CLOSED: [2018-07-20 Fri 11:25]
   - State "DONE"       from "STARTED"    [2018-07-20 Fri 11:25]
   Out of the box, Laravel ships with a small bit of boilterplate to get you up and running as quickly as possible. Specifically, it includes a few Sass and Vue suggestions. However, as part of Laravel 5.5, you may now configure this initial boilterplate top your liking. Want to strip all of it? Now you can. Prefer to use React instead of Vue? Easy!
   =php artisan preset:none=
