* STARTED What's New in Laravel 5.1
  Laravel 5.1 includes a variety of welcomed new features. Everything from broadcasting events, to massively improved testing facilities, to LTS support. As always, Laravel is setting the curve with this new release. Let's breeze through the new features that you'll be enjoying.

** DONE Adopting PSR-2
   CLOSED: [2018-07-18 Wed 09:19]
   - State "DONE"       from "STARTED"    [2018-07-18 Wed 09:19]
   Upon installing Laravel 5.1, the first thing you'll notice is that the style guide is a bit different. Laravel now adopts the PSR-2 coding standard. If you're not familiar, this is nothing more than a set of style guidelines for writing code.

** DONE Injecting Services With Blade
   CLOSED: [2018-07-18 Wed 09:33]
   - State "DONE"       from "STARTED"    [2018-07-18 Wed 09:33]
   Inspired by ASP.NET MVC 6, you may now inject services directly into your views. While it's not appropriate for everything, there are a number of situations where this technique will prove to be quite useful. Let me show you.
   - Method 1: View Composer
     #+BEGIN_SRC php
       View::composer('stats', function($view) {
           return $view->with('stats', app('App\Stats'));
       })
     #+END_SRC
   - Method 2: Inject in the =stats.blade.php=
     #+BEGIN_SRC php
       @inject('stats', 'App\Stats')
     #+END_SRC

** DONE Elixir Improvements
   CLOSED: [2018-07-18 Wed 10:04]
   - State "DONE"       from "STARTED"    [2018-07-18 Wed 10:04]
   In addition to a series of optimizations and consistency improvements, in Laravel 5.1, Elixir includes EcmaScript 6 compilation right out of the box, using the excellent Babel compiler.
   - ES2015 function
     #+BEGIN_SRC js
       let fun = () => true;


       let fun2 = a => a > 10;
       let fun3 = (a) => a > 10;
     #+END_SRC

** DONE Better Testing Facilities
   CLOSED: [2018-07-18 Wed 10:20]
   - State "DONE"       from "STARTED"    [2018-07-18 Wed 10:20]
   If you worked through the =Intuitive Integration Testing= series, you'll feel right at home in 5.1. Most of that API is now part of the base install. This means, you'll be writing incredibly readable integration tests in no time.

** DONE Model Factories
   CLOSED: [2018-07-18 Wed 11:22]
   - State "DONE"       from "STARTED"    [2018-07-18 Wed 11:22]
   Whether for database seeding or general testing, you're going to love model factories in Laravel 5.1. A single line of code can give you a huge amount of convenience and power.
